baseURL = 'https://zverovich.net/'
languageCode = 'en-us'
title = 'zverovich.net'
theme = 'diary'
ignoreFiles = 'static/slides'

[markup]
  [markup.highlight]
    style = 'monokailight'

[markup.goldmark.renderer]
  unsafe= true

[menus]
[[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 10
[[menus.main]]
    name = 'Papers'
    pageRef = '/papers'
    weight = 20

[params]
  disqusShortname = 'zverovich'

[services]
  [services.googleAnalytics]
    ID = 'G-0XZ98BDDTK'
