baseURL = 'https://vitaut.net/'
languageCode = 'en-us'
title = 'vitaut.net'
theme = 'diary'
ignoreFiles = 'static/slides'

[markup]
  [markup.highlight]
    style = 'monokailight'

[markup.goldmark.renderer]
  unsafe= true

[params]
  disqusShortname = 'zverovich'

[services]
  [services.googleAnalytics]
    ID = 'G-0XZ98BDDTK'

[menus]
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 10
  [[menus.main]]
    name = 'Talks'
    pageRef = '/talks'
    weight = 20
  [[menus.main]]
    name = 'Papers'
    pageRef = '/papers'
    weight = 30
  [[menus.main]]
    name = 'Projects'
    pageRef = '/projects'
    weight = 40

[[params.socialIcons]]
  name = 'github'
  url = 'https://github.com/vitaut'
